use crate::model::macros;
use shared::model::MetadataUpdateConfigDto;

#[derive(Debug, Clone)]
pub struct MetadataUpdateConfig {
    pub queue_log_interval: String,
    pub queue_log_interval_secs: u64,
    pub progress_log_interval: String,
    pub progress_log_interval_secs: u64,
    pub max_resolve_retry_backoff: String,
    pub max_resolve_retry_backoff_secs: u64,
    pub resolve_min_retry_base: String,
    pub resolve_min_retry_base_secs: u64,
    pub resolve_exhaustion_reset_gap: String,
    pub resolve_exhaustion_reset_gap_secs: u64,
    pub probe_cooldown: String,
    pub probe_cooldown_secs: u64,
    pub retry_delay: String,
    pub t_retry_delay_secs: u64,
    pub probe_retry_load_retry_delay: String,
    pub probe_retry_load_retry_delay_secs: u64,
    pub worker_idle_timeout: String,
    pub worker_idle_timeout_secs: u64,
    pub probe_retry_backoff_step_1: String,
    pub probe_retry_backoff_step_1_secs: u64,
    pub probe_retry_backoff_step_2: String,
    pub probe_retry_backoff_step_2_secs: u64,
    pub probe_retry_backoff_step_3: String,
    pub probe_retry_backoff_step_3_secs: u64,
    pub max_attempts_resolve: u8,
    pub max_attempts_probe: u8,
    pub backoff_jitter_percent: u8,
    pub max_queue_size: usize,
    pub ffprobe_enabled: bool,
    pub ffprobe_timeout: Option<u64>,
    pub ffprobe_analyze_duration: String,
    pub t_ffprobe_analyze_duration_micros: u64,
    pub ffprobe_probe_size: String,
    pub t_ffprobe_probe_size_bytes: u64,
    pub ffprobe_live_analyze_duration: String,
    pub t_ffprobe_live_analyze_duration_micros: u64,
    pub ffprobe_live_probe_size: String,
    pub t_ffprobe_live_probe_size_bytes: u64,
}

impl Default for MetadataUpdateConfig {
    fn default() -> Self { Self::from(&MetadataUpdateConfigDto::default()) }
}

macros::from_impl!(MetadataUpdateConfig);

impl From<&MetadataUpdateConfigDto> for MetadataUpdateConfig {
    fn from(dto: &MetadataUpdateConfigDto) -> Self {
        Self {
            queue_log_interval: dto.queue_log_interval.clone(),
            queue_log_interval_secs: dto.queue_log_interval_secs,
            progress_log_interval: dto.progress_log_interval.clone(),
            progress_log_interval_secs: dto.progress_log_interval_secs,
            max_resolve_retry_backoff: dto.max_resolve_retry_backoff.clone(),
            max_resolve_retry_backoff_secs: dto.max_resolve_retry_backoff_secs,
            resolve_min_retry_base: dto.resolve_min_retry_base.clone(),
            resolve_min_retry_base_secs: dto.resolve_min_retry_base_secs,
            resolve_exhaustion_reset_gap: dto.resolve_exhaustion_reset_gap.clone(),
            resolve_exhaustion_reset_gap_secs: dto.resolve_exhaustion_reset_gap_secs,
            probe_cooldown: dto.probe_cooldown.clone(),
            probe_cooldown_secs: dto.probe_cooldown_secs,
            retry_delay: dto.retry_delay.clone(),
            t_retry_delay_secs: dto.t_retry_delay_secs,
            probe_retry_load_retry_delay: dto.probe_retry_load_retry_delay.clone(),
            probe_retry_load_retry_delay_secs: dto.probe_retry_load_retry_delay_secs,
            worker_idle_timeout: dto.worker_idle_timeout.clone(),
            worker_idle_timeout_secs: dto.worker_idle_timeout_secs,
            probe_retry_backoff_step_1: dto.probe_retry_backoff_step_1.clone(),
            probe_retry_backoff_step_1_secs: dto.probe_retry_backoff_step_1_secs,
            probe_retry_backoff_step_2: dto.probe_retry_backoff_step_2.clone(),
            probe_retry_backoff_step_2_secs: dto.probe_retry_backoff_step_2_secs,
            probe_retry_backoff_step_3: dto.probe_retry_backoff_step_3.clone(),
            probe_retry_backoff_step_3_secs: dto.probe_retry_backoff_step_3_secs,
            max_attempts_resolve: dto.max_attempts_resolve,
            max_attempts_probe: dto.max_attempts_probe,
            backoff_jitter_percent: dto.backoff_jitter_percent,
            max_queue_size: dto.max_queue_size,
            ffprobe_enabled: dto.ffprobe_enabled,
            ffprobe_timeout: dto.ffprobe_timeout,
            ffprobe_analyze_duration: dto.ffprobe_analyze_duration.clone(),
            t_ffprobe_analyze_duration_micros: dto.t_ffprobe_analyze_duration_micros,
            ffprobe_probe_size: dto.ffprobe_probe_size.clone(),
            t_ffprobe_probe_size_bytes: dto.t_ffprobe_probe_size_bytes,
            ffprobe_live_analyze_duration: dto.ffprobe_live_analyze_duration.clone(),
            t_ffprobe_live_analyze_duration_micros: dto.t_ffprobe_live_analyze_duration_micros,
            ffprobe_live_probe_size: dto.ffprobe_live_probe_size.clone(),
            t_ffprobe_live_probe_size_bytes: dto.t_ffprobe_live_probe_size_bytes,
        }
    }
}

impl From<&MetadataUpdateConfig> for MetadataUpdateConfigDto {
    fn from(instance: &MetadataUpdateConfig) -> Self {
        Self {
            queue_log_interval: instance.queue_log_interval.clone(),
            queue_log_interval_secs: instance.queue_log_interval_secs,
            progress_log_interval: instance.progress_log_interval.clone(),
            progress_log_interval_secs: instance.progress_log_interval_secs,
            max_resolve_retry_backoff: instance.max_resolve_retry_backoff.clone(),
            max_resolve_retry_backoff_secs: instance.max_resolve_retry_backoff_secs,
            resolve_min_retry_base: instance.resolve_min_retry_base.clone(),
            resolve_min_retry_base_secs: instance.resolve_min_retry_base_secs,
            resolve_exhaustion_reset_gap: instance.resolve_exhaustion_reset_gap.clone(),
            resolve_exhaustion_reset_gap_secs: instance.resolve_exhaustion_reset_gap_secs,
            probe_cooldown: instance.probe_cooldown.clone(),
            probe_cooldown_secs: instance.probe_cooldown_secs,
            retry_delay: instance.retry_delay.clone(),
            t_retry_delay_secs: instance.t_retry_delay_secs,
            probe_retry_load_retry_delay: instance.probe_retry_load_retry_delay.clone(),
            probe_retry_load_retry_delay_secs: instance.probe_retry_load_retry_delay_secs,
            worker_idle_timeout: instance.worker_idle_timeout.clone(),
            worker_idle_timeout_secs: instance.worker_idle_timeout_secs,
            probe_retry_backoff_step_1: instance.probe_retry_backoff_step_1.clone(),
            probe_retry_backoff_step_1_secs: instance.probe_retry_backoff_step_1_secs,
            probe_retry_backoff_step_2: instance.probe_retry_backoff_step_2.clone(),
            probe_retry_backoff_step_2_secs: instance.probe_retry_backoff_step_2_secs,
            probe_retry_backoff_step_3: instance.probe_retry_backoff_step_3.clone(),
            probe_retry_backoff_step_3_secs: instance.probe_retry_backoff_step_3_secs,
            max_attempts_resolve: instance.max_attempts_resolve,
            max_attempts_probe: instance.max_attempts_probe,
            backoff_jitter_percent: instance.backoff_jitter_percent,
            max_queue_size: instance.max_queue_size,
            ffprobe_enabled: instance.ffprobe_enabled,
            ffprobe_timeout: instance.ffprobe_timeout,
            ffprobe_analyze_duration: instance.ffprobe_analyze_duration.clone(),
            t_ffprobe_analyze_duration_micros: instance.t_ffprobe_analyze_duration_micros,
            ffprobe_probe_size: instance.ffprobe_probe_size.clone(),
            t_ffprobe_probe_size_bytes: instance.t_ffprobe_probe_size_bytes,
            ffprobe_live_analyze_duration: instance.ffprobe_live_analyze_duration.clone(),
            t_ffprobe_live_analyze_duration_micros: instance.t_ffprobe_live_analyze_duration_micros,
            ffprobe_live_probe_size: instance.ffprobe_live_probe_size.clone(),
            t_ffprobe_live_probe_size_bytes: instance.t_ffprobe_live_probe_size_bytes,
        }
    }
}
