[package]
name = "tuliprox-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Authentication primitives and access control for tuliprox"

[lints]
workspace = true

[dependencies]
shared = { workspace = true }
tuliprox-core = { workspace = true }
tuliprox-repository = { workspace = true }
arc-swap.workspace = true
axum = { version = "0.8.9", features = ["macros", "default", "ws"] }
base64.workspace = true
blake3.workspace = true
chrono.workspace = true
dashmap.workspace = true
jsonwebtoken = { version = "10.4.0", default-features = false, features = ["aws_lc_rs"] }
log.workspace = true
rand = "0.9.5"
rust-argon2 = "3.0.0"
serde_json = { workspace = true, features = ["raw_value", "preserve_order"] }
thiserror.workspace = true
rpassword = "7.5.4"
zeroize.workspace = true
