//! DVR recording domain types.
//!
//! This module is the source of truth for `RecordingMetadata`; persistence,
//! runtime, and DTO layers all mirror it.

use super::identity_registry::UserId;
use std::fmt;

/// Public DTO for the recording half of a transfer task. Filters server-
/// internal fields (source identifiers, internal partial paths, raw
/// `target_id`/`virtual_id`/`input_name`, notification markers, transitional
/// `Deleting` state) so the API never leaks another user's owner identity or
/// the worker-internal relative paths.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingTaskDto {
    /// `Some(UserId)` for normal recordings; `None` for legacy admin records
    /// (caller authorization decides whether the record is visible at all).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<UserId>,
    pub visibility: RecordingVisibility,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_start: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_end: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_start: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_end: Option<i64>,
    pub pre_roll_secs: u64,
    pub post_roll_secs: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<i64>,
    /// Filename component of the final relative path. Server does not
    /// expose directory structure or the recording root.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub epg: Option<EpgEpisodeMetadata>,
    /// Immutable provenance for tasks generated by a recurring rule.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurrence_key: Option<String>,
}

impl RecordingTaskDto {
    /// Project a `RecordingMetadata` into a public DTO. Filters server-only
    /// fields and derives `filename` from the final relative path's last
    /// component.
    pub fn from_metadata(meta: &RecordingMetadata) -> Self {
        let owner_id = match &meta.owner {
            RecordingOwner::User(uid) => Some(uid.clone()),
            RecordingOwner::LegacyAdmin => None,
        };
        let filename = meta.relative_path.as_deref().and_then(extract_filename_component);
        Self {
            owner_id,
            visibility: meta.visibility,
            channel_id: meta.channel_id.clone(),
            channel_name: meta.channel_name.clone(),
            program_title: meta.program_title.clone(),
            program_start: meta.program_start,
            program_end: meta.program_end,
            scheduled_start: meta.scheduled_start,
            scheduled_end: meta.scheduled_end,
            pre_roll_secs: meta.pre_roll_secs,
            post_roll_secs: meta.post_roll_secs,
            completed_at: meta.completed_at,
            filename: filename.map(str::to_string),
            epg: meta.epg.clone(),
            rule_id: meta.provenance.rule_id.clone(),
            occurrence_key: meta.provenance.occurrence_key.clone(),
        }
    }
}

fn extract_filename_component(relative_path: &str) -> Option<&str> {
    let trimmed = relative_path.trim_end_matches('/');
    if trimmed.is_empty() {
        return None;
    }
    std::path::Path::new(trimmed).file_name().and_then(|s| s.to_str())
}

/// Recording owner. `LegacyAdmin` is migration-only and only valid for
/// records loaded from a pre-DVR persisted state.
///
/// Adjacently tagged so the newtype `User(UserId)` can serialize: the
/// content field name is `user`, matching what the queue pre-scan in
/// `backend::download` looks for.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", content = "user", rename_all = "snake_case")]
pub enum RecordingOwner {
    User(UserId),
    LegacyAdmin,
}

impl RecordingOwner {
    pub fn is_legacy_admin(&self) -> bool { matches!(self, Self::LegacyAdmin) }
}

/// Recording visibility. Shared recordings are visible to every user with
/// `recording.read`; private recordings are visible only to the owner.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecordingVisibility {
    #[default]
    Private,
    Shared,
}

/// Server-owned source identifiers. The stream URL is never accepted from a
/// client; the server resolves it from these identifiers at execute time.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingSource {
    pub target_id: String,
    pub virtual_id: String,
    pub input_name: String,
    #[serde(default)]
    pub cluster: super::XtreamCluster,
}

impl RecordingSource {
    pub fn new(target_id: impl Into<String>, virtual_id: impl Into<String>, input_name: impl Into<String>) -> Self {
        Self {
            target_id: target_id.into(),
            virtual_id: virtual_id.into(),
            input_name: input_name.into(),
            cluster: super::XtreamCluster::Live,
        }
    }

    pub fn with_cluster(mut self, cluster: super::XtreamCluster) -> Self {
        self.cluster = cluster;
        self
    }
}

/// EPG episode metadata with tri-state airing provenance.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
pub struct EpgEpisodeMetadata {
    pub programme_id: Option<String>,
    pub series_id: Option<String>,
    pub episode_id: Option<String>,
    pub season: Option<u32>,
    pub episode: Option<u32>,
    #[serde(default)]
    pub airing: AiringStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum AiringStatus {
    #[default]
    Unknown,
    New,
    Repeat,
}

/// Lifecycle notification marker persisted alongside the task. At-most-once
/// delivery is enforced by recording this marker in the same queue mutation
/// as the lifecycle transition; the notification adapter is gated on it.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum NotificationMarkerKind {
    Started,
    Completed,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct NotificationMarker {
    pub kind: NotificationMarkerKind,
    pub attempted_at: i64,
}

impl NotificationMarker {
    pub fn new(kind: NotificationMarkerKind, attempted_at: i64) -> Self { Self { kind, attempted_at } }
}

/// Recurring-rule provenance. `rule_id` and `occurrence_key` are immutable for
/// the life of a task; the rule may be deleted but the task retains the
/// historical values.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
pub struct RecordingProvenance {
    pub rule_id: Option<String>,
    pub occurrence_key: Option<String>,
}

/// Terminal state of a task before deletion began. Only `Completed`, `Failed`,
/// and `Cancelled` are valid previous states; the worker rejects transitions
/// from `Scheduled`/`Queued`/`Downloading`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DeletionPreviousState {
    Completed,
    Failed,
    Cancelled,
}

impl DeletionPreviousState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }
}

/// Recording metadata. Only present when `FileDownload.kind == Recording`.
/// Invariant: `RecordingMetadata` is required iff the kind is Recording, and
/// `recording == None` iff the kind is Download (after normalization).
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingMetadata {
    pub owner: RecordingOwner,
    pub visibility: RecordingVisibility,
    /// `None` for legacy records; required for new recordings.
    pub source: Option<RecordingSource>,
    /// Original EPG interval (Unix seconds).
    pub program_start: Option<i64>,
    pub program_end: Option<i64>,
    /// Effective padded interval (Unix seconds). When the program is
    /// currently airing, this is clamped to `now..scheduled_end`.
    pub scheduled_start: Option<i64>,
    pub scheduled_end: Option<i64>,
    pub pre_roll_secs: u64,
    pub post_roll_secs: u64,
    pub channel_id: Option<String>,
    pub channel_name: Option<String>,
    pub program_title: Option<String>,
    pub epg: Option<EpgEpisodeMetadata>,
    #[serde(default)]
    pub provenance: RecordingProvenance,
    /// Final relative path below the recording root. `None` until the task
    /// is reserved or finalized.
    pub relative_path: Option<String>,
    /// Worker-owned partial path while a recording is in progress.
    pub partial_relative_path: Option<String>,
    /// Conservative quota reservation. `0` once the task completes.
    pub reserved_bytes: u64,
    /// Measured partial/final size. Authoritative once the task completes.
    pub measured_bytes: u64,
    /// Actual completion timestamp. For migrated records, derived from a
    /// safe file mtime then the scheduled end.
    pub completed_at: Option<i64>,
    /// Persisted at-most-once notification markers.
    #[serde(default)]
    pub notification_markers: Vec<NotificationMarker>,
    /// Terminal-only previous state while a deletion is in progress. `None`
    /// outside the `Deleting` transitional state.
    pub deleting_previous_state: Option<DeletionPreviousState>,
}

impl RecordingMetadata {
    /// Build metadata for a freshly created recording. Requires a server-owned
    /// source. Validates the kind-relative invariants.
    pub fn new(
        owner: RecordingOwner,
        visibility: RecordingVisibility,
        source: RecordingSource,
        program_start: i64,
        program_end: i64,
        pre_roll_secs: u64,
        post_roll_secs: u64,
    ) -> Self {
        let scheduled_start = program_start.saturating_sub(pre_roll_secs as i64);
        let scheduled_end = program_end.saturating_add(post_roll_secs as i64);
        Self {
            owner,
            visibility,
            source: Some(source),
            program_start: Some(program_start),
            program_end: Some(program_end),
            scheduled_start: Some(scheduled_start),
            scheduled_end: Some(scheduled_end),
            pre_roll_secs,
            post_roll_secs,
            channel_id: None,
            channel_name: None,
            program_title: None,
            epg: None,
            provenance: RecordingProvenance::default(),
            relative_path: None,
            partial_relative_path: None,
            reserved_bytes: 0,
            measured_bytes: 0,
            completed_at: None,
            notification_markers: Vec::new(),
            deleting_previous_state: None,
        }
    }

    /// Build metadata for a legacy admin record loaded from pre-DVR persisted
    /// state. The source is `None` and the program/scheduled intervals are
    /// derived from the legacy start/duration if provided.
    pub fn for_legacy_admin(scheduled_start: i64, duration_secs: u64) -> Self {
        let program_start = scheduled_start;
        let program_end = scheduled_start.saturating_add(duration_secs as i64);
        Self {
            owner: RecordingOwner::LegacyAdmin,
            visibility: RecordingVisibility::Private,
            source: None,
            program_start: Some(program_start),
            program_end: Some(program_end),
            scheduled_start: Some(program_start),
            scheduled_end: Some(program_end),
            pre_roll_secs: 0,
            post_roll_secs: 0,
            channel_id: None,
            channel_name: None,
            program_title: None,
            epg: None,
            provenance: RecordingProvenance::default(),
            relative_path: None,
            partial_relative_path: None,
            reserved_bytes: 0,
            measured_bytes: 0,
            completed_at: None,
            notification_markers: Vec::new(),
            deleting_previous_state: None,
        }
    }

    pub fn is_deleting(&self) -> bool { self.deleting_previous_state.is_some() }
}

/// Monotonic revision counter for the persisted download queue. Increments
/// once per committed queue mutation. Stored alongside the queue snapshot.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct QueueRevision(pub u64);

impl fmt::Display for QueueRevision {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { write!(f, "{}", self.0) }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn legacy_recording_source_defaults_to_live_cluster() {
        let source: RecordingSource =
            serde_json::from_str(r#"{"target_id":"target","virtual_id":"42","input_name":"input-a"}"#)
                .expect("deserialize legacy source");

        assert_eq!(source.cluster, super::super::XtreamCluster::Live);
    }

    #[test]
    fn new_metadata_carries_full_intervals_and_source() {
        let source = RecordingSource::new("target-1", "v-1", "input-a");
        let meta = RecordingMetadata::new(
            RecordingOwner::User(UserId::from("web:abc")),
            RecordingVisibility::Private,
            source,
            1_700_000_000,
            1_700_000_900,
            60,
            120,
        );
        assert_eq!(meta.scheduled_start, Some(1_700_000_000 - 60));
        assert_eq!(meta.scheduled_end, Some(1_700_000_900 + 120));
        assert_eq!(meta.pre_roll_secs, 60);
        assert_eq!(meta.post_roll_secs, 120);
        assert!(meta.source.is_some());
        assert!(!meta.is_deleting());
    }

    #[test]
    fn legacy_admin_metadata_has_no_source_and_zero_padding() {
        let meta = RecordingMetadata::for_legacy_admin(1_700_000_000, 3_600);
        assert!(meta.source.is_none());
        assert!(meta.owner.is_legacy_admin());
        assert_eq!(meta.pre_roll_secs, 0);
        assert_eq!(meta.post_roll_secs, 0);
        assert_eq!(meta.scheduled_start, Some(1_700_000_000));
        assert_eq!(meta.scheduled_end, Some(1_700_003_600));
    }

    #[test]
    fn recording_owner_user_round_trips_as_adjacent_tag() {
        let owner = RecordingOwner::User(UserId::from("web:alice"));
        let json = serde_json::to_string(&owner).expect("serialize");
        assert_eq!(json, r#"{"kind":"user","user":"web:alice"}"#);
        let restored: RecordingOwner = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, owner);
    }

    #[test]
    fn recording_owner_legacy_admin_round_trips() {
        let owner = RecordingOwner::LegacyAdmin;
        let json = serde_json::to_string(&owner).expect("serialize");
        assert_eq!(json, r#"{"kind":"legacy_admin"}"#);
        let restored: RecordingOwner = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, owner);
    }

    #[test]
    fn deleting_state_round_trip() {
        let mut meta = RecordingMetadata::for_legacy_admin(1_700_000_000, 60);
        assert!(!meta.is_deleting());
        meta.deleting_previous_state = Some(DeletionPreviousState::Completed);
        assert!(meta.is_deleting());
        let json = serde_json::to_string(&meta).expect("serialize");
        let restored: RecordingMetadata = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored.deleting_previous_state, Some(DeletionPreviousState::Completed));
    }

    #[test]
    fn notification_marker_serialization() {
        let marker = NotificationMarker::new(NotificationMarkerKind::Completed, 1_700_000_000);
        let json = serde_json::to_string(&marker).expect("serialize");
        assert!(json.contains("\"completed\""), "{json}");
    }

    #[test]
    fn queue_revision_default_is_zero() {
        assert_eq!(QueueRevision::default().0, 0);
        assert_eq!(format!("{}", QueueRevision(42)), "42");
    }

    // --- RecordingTaskDto tests ---

    use super::super::transfer::{TaskKindDto, TaskPriorityDto, TransferStatusDto, TransferTaskDto};

    fn make_test_metadata() -> RecordingMetadata {
        let mut meta = RecordingMetadata::for_legacy_admin(1_700_000_000, 3_600);
        meta.owner = RecordingOwner::User(UserId::from("web:abc"));
        meta.visibility = RecordingVisibility::Private;
        meta.channel_id = Some("ch-1".to_string());
        meta.channel_name = Some("Channel One".to_string());
        meta.program_title = Some("Pilot".to_string());
        meta.relative_path = Some("users/web:abc/pilot.ts".to_string());
        meta.partial_relative_path = Some("users/web:abc/.pilot.ts.partial".to_string());
        meta.completed_at = Some(1_700_000_000);
        meta.provenance =
            RecordingProvenance { rule_id: Some("rule-1".to_string()), occurrence_key: Some("occ-1".to_string()) };
        meta.epg = Some(EpgEpisodeMetadata {
            programme_id: Some("prog-1".to_string()),
            series_id: Some("series-1".to_string()),
            episode_id: Some("ep-1".to_string()),
            season: Some(1),
            episode: Some(2),
            airing: AiringStatus::New,
        });
        meta
    }

    #[test]
    fn recording_task_dto_omits_internal_fields() {
        let meta = make_test_metadata();
        let dto = RecordingTaskDto::from_metadata(&meta);
        // No source, no notification_markers, no deleting state, no
        // measured/reserved bytes, no partial path.
        let json = serde_json::to_value(&dto).expect("serialize");
        assert!(json.get("owner_id").is_some());
        assert!(json.get("source").is_none(), "source must not leak");
        assert!(json.get("notification_markers").is_none(), "markers must not leak");
        assert!(json.get("deleting_previous_state").is_none(), "deleting state must not leak");
        assert!(json.get("reserved_bytes").is_none(), "reserved bytes must not leak");
        assert!(json.get("measured_bytes").is_none(), "measured bytes must not leak");
        assert!(json.get("partial_relative_path").is_none(), "partial path must not leak");
    }

    #[test]
    fn recording_task_dto_extracts_filename_from_relative_path() {
        let meta = make_test_metadata();
        let dto = RecordingTaskDto::from_metadata(&meta);
        assert_eq!(dto.filename.as_deref(), Some("pilot.ts"));
    }

    #[test]
    fn recording_task_dto_legacy_admin_has_no_owner_id() {
        let meta = RecordingMetadata::for_legacy_admin(1_700_000_000, 60);
        let dto = RecordingTaskDto::from_metadata(&meta);
        assert!(dto.owner_id.is_none());
    }

    #[test]
    fn recording_task_dto_round_trips() {
        let meta = make_test_metadata();
        let dto = RecordingTaskDto::from_metadata(&meta);
        let json = serde_json::to_string(&dto).expect("serialize");
        let restored: RecordingTaskDto = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, dto);
    }

    #[test]
    fn transfer_task_dto_with_recording_round_trips() {
        let task = TransferTaskDto {
            id: "rec-1".to_string(),
            title: "Pilot".to_string(),
            kind: TaskKindDto::Recording,
            priority: TaskPriorityDto::Normal,
            status: TransferStatusDto::Scheduled,
            retry_attempts: 0,
            downloaded_bytes: 0,
            total_bytes: None,
            next_retry_at: None,
            scheduled_start_at: Some(1_700_000_000),
            duration_secs: Some(3_600),
            error: None,
            recording: Some(RecordingTaskDto::from_metadata(&make_test_metadata())),
        };
        let json = serde_json::to_string(&task).expect("serialize");
        let restored: TransferTaskDto = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, task);
    }

    #[test]
    fn transfer_task_dto_without_recording_field_loads_for_backward_compat() {
        // Old serialized payloads must keep loading after adding the new
        // `recording` field. The DTO uses `#[serde(default)]` on that field.
        let legacy = r#"{
            "id": "abc",
            "title": "Example",
            "kind": "download",
            "priority": "background",
            "status": "queued",
            "retry_attempts": 0,
            "downloaded_bytes": 123
        }"#;
        let restored: TransferTaskDto = serde_json::from_str(legacy).expect("legacy payload should load");
        assert_eq!(restored.id, "abc");
        assert!(restored.recording.is_none());
    }
}
