//! DVR recording domain types.
//!
//! See `docs/superpowers/specs/2026-07-23-extended-dvr-design.md` and the
//! matching plan for the full design. This module is the source of truth for
//! `RecordingMetadata`; persistence, runtime, and DTO layers all mirror it.

use super::{
    identity_registry::UserId,
    transfer::{TaskPriorityDto, TransferStatusDto},
};
use std::fmt;

/// Media kind of a recording task. Determined by the server from the
/// resolved catalog item; never accepted from a client.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecordingKind {
    /// Scheduled live capture. Executed with ffmpeg, never resumable.
    Live,
    /// Video on demand. Executed over resumable HTTP.
    Vod,
    /// Series episode. Executed over resumable HTTP.
    Series,
}

impl RecordingKind {
    /// Live is captured within a programme window; VOD and Series run to EOF.
    pub fn is_scheduled(self) -> bool { matches!(self, Self::Live) }

    /// Only VOD and Series may be paused and resumed.
    pub fn is_resumable(self) -> bool { matches!(self, Self::Vod | Self::Series) }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Live => "live",
            Self::Vod => "vod",
            Self::Series => "series",
        }
    }
}

impl fmt::Display for RecordingKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { f.write_str(self.as_str()) }
}

/// Owner-safe public projection of a recording task. This is the only
/// recording shape crossing the API or WebSocket boundary. It never carries
/// the source URL, provider/source identifiers, configured headers,
/// absolute/relative/partial paths, transfer validators, or another user's
/// owner identifier.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingTaskDto {
    pub id: String,
    pub title: String,
    pub kind: RecordingKind,
    pub priority: TaskPriorityDto,
    pub status: TransferStatusDto,
    pub retry_attempts: u8,
    pub transferred_bytes: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_retry_at: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// `Some` only when the viewer owns the task; never another user's id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<UserId>,
    pub visibility: RecordingVisibility,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_start: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub program_end: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_start: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_end: Option<i64>,
    pub pre_roll_secs: u64,
    pub post_roll_secs: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<i64>,
    /// Filename component of the final relative path. The server does not
    /// expose the directory structure or the recording root.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub epg: Option<EpgEpisodeMetadata>,
    /// Immutable provenance for tasks generated by a recurring rule.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurrence_key: Option<String>,
}

impl RecordingTaskDto {
    /// Lifecycle partition for the UI: non-terminal tasks are current,
    /// terminal ones are completed.
    pub fn is_terminal(&self) -> bool {
        matches!(self.status, TransferStatusDto::Completed | TransferStatusDto::Failed | TransferStatusDto::Cancelled)
    }

    /// Effective duration of a scheduled window, when both bounds are known.
    pub fn scheduled_duration_secs(&self) -> Option<u64> {
        let (start, end) = self.scheduled_start.zip(self.scheduled_end)?;
        u64::try_from(end.saturating_sub(start)).ok()
    }
}

/// Recording owner. Every task is owned by exactly one user; there is no
/// unowned or admin-legacy record.
///
/// Adjacently tagged so the newtype `User(UserId)` serializes with the
/// content field name `user`.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", content = "user", rename_all = "snake_case")]
pub enum RecordingOwner {
    User(UserId),
}

impl RecordingOwner {
    pub fn user_id(&self) -> &UserId {
        let Self::User(uid) = self;
        uid
    }
}

/// Recording visibility. Shared recordings are visible to every user with
/// `recording.read`; private recordings are visible only to the owner.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecordingVisibility {
    #[default]
    Private,
    Shared,
}

/// Server-owned source identifiers. The stream URL is never accepted from a
/// client; the server resolves it from these identifiers at execute time.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingSource {
    pub target_id: String,
    pub virtual_id: String,
    pub input_name: String,
    #[serde(default)]
    pub cluster: super::XtreamCluster,
}

impl RecordingSource {
    pub fn new(target_id: impl Into<String>, virtual_id: impl Into<String>, input_name: impl Into<String>) -> Self {
        Self {
            target_id: target_id.into(),
            virtual_id: virtual_id.into(),
            input_name: input_name.into(),
            cluster: super::XtreamCluster::Live,
        }
    }

    pub fn with_cluster(mut self, cluster: super::XtreamCluster) -> Self {
        self.cluster = cluster;
        self
    }
}

/// EPG episode metadata with tri-state airing provenance.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
pub struct EpgEpisodeMetadata {
    pub programme_id: Option<String>,
    pub series_id: Option<String>,
    pub episode_id: Option<String>,
    pub season: Option<u32>,
    pub episode: Option<u32>,
    #[serde(default)]
    pub airing: AiringStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum AiringStatus {
    #[default]
    Unknown,
    New,
    Repeat,
}

/// Lifecycle notification marker persisted alongside the task. At-most-once
/// delivery is enforced by recording this marker in the same queue mutation
/// as the lifecycle transition; the notification adapter is gated on it.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum NotificationMarkerKind {
    Started,
    Completed,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct NotificationMarker {
    pub kind: NotificationMarkerKind,
    pub attempted_at: i64,
}

impl NotificationMarker {
    pub fn new(kind: NotificationMarkerKind, attempted_at: i64) -> Self { Self { kind, attempted_at } }
}

/// Recurring-rule provenance. `rule_id` and `occurrence_key` are immutable for
/// the life of a task; the rule may be deleted but the task retains the
/// historical values.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, Default)]
pub struct RecordingProvenance {
    pub rule_id: Option<String>,
    pub occurrence_key: Option<String>,
}

/// Terminal state of a task before deletion began. Only `Completed`, `Failed`,
/// and `Cancelled` are valid previous states; the worker rejects transitions
/// from `Scheduled`/`Queued`/`Running`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DeletionPreviousState {
    Completed,
    Failed,
    Cancelled,
}

impl DeletionPreviousState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }
}

/// Recording metadata. Every recording task carries exactly one of these;
/// the programme interval fields are populated for `RecordingKind::Live`
/// only.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RecordingMetadata {
    pub owner: RecordingOwner,
    pub visibility: RecordingVisibility,
    /// Server-owned source identity. Never client supplied.
    pub source: RecordingSource,
    /// Original EPG interval (Unix seconds). Live only.
    pub program_start: Option<i64>,
    pub program_end: Option<i64>,
    /// Effective padded interval (Unix seconds). When the program is
    /// currently airing, this is clamped to `now..scheduled_end`. Live only.
    pub scheduled_start: Option<i64>,
    pub scheduled_end: Option<i64>,
    pub pre_roll_secs: u64,
    pub post_roll_secs: u64,
    pub channel_id: Option<String>,
    pub channel_name: Option<String>,
    pub program_title: Option<String>,
    pub epg: Option<EpgEpisodeMetadata>,
    #[serde(default)]
    pub provenance: RecordingProvenance,
    /// Final relative path below the recording root. `None` until the task
    /// is reserved or finalized.
    pub relative_path: Option<String>,
    /// Worker-owned partial path while a recording is in progress.
    pub partial_relative_path: Option<String>,
    /// Conservative quota reservation. `0` once the task completes.
    pub reserved_bytes: u64,
    /// Measured partial/final size. Authoritative once the task completes.
    pub measured_bytes: u64,
    /// Actual completion timestamp.
    pub completed_at: Option<i64>,
    /// Persisted at-most-once notification markers.
    #[serde(default)]
    pub notification_markers: Vec<NotificationMarker>,
    /// Terminal-only previous state while a deletion is in progress. `None`
    /// outside the `Deleting` transitional state.
    pub deleting_previous_state: Option<DeletionPreviousState>,
}

impl RecordingMetadata {
    /// Build metadata for a scheduled live recording.
    pub fn new_live(
        owner: RecordingOwner,
        visibility: RecordingVisibility,
        source: RecordingSource,
        program_start: i64,
        program_end: i64,
        pre_roll_secs: u64,
        post_roll_secs: u64,
    ) -> Self {
        let scheduled_start = program_start.saturating_sub(pre_roll_secs as i64);
        let scheduled_end = program_end.saturating_add(post_roll_secs as i64);
        Self {
            owner,
            visibility,
            source,
            program_start: Some(program_start),
            program_end: Some(program_end),
            scheduled_start: Some(scheduled_start),
            scheduled_end: Some(scheduled_end),
            pre_roll_secs,
            post_roll_secs,
            channel_id: None,
            channel_name: None,
            program_title: None,
            epg: None,
            provenance: RecordingProvenance::default(),
            relative_path: None,
            partial_relative_path: None,
            reserved_bytes: 0,
            measured_bytes: 0,
            completed_at: None,
            notification_markers: Vec::new(),
            deleting_previous_state: None,
        }
    }

    /// Build metadata for an immediate VOD or series-episode transfer. These
    /// have no programme window and no padding.
    pub fn new_media(
        owner: RecordingOwner,
        visibility: RecordingVisibility,
        source: RecordingSource,
        title: String,
    ) -> Self {
        Self {
            program_start: None,
            program_end: None,
            scheduled_start: None,
            scheduled_end: None,
            program_title: Some(title),
            ..Self::new_live(owner, visibility, source, 0, 0, 0, 0)
        }
    }

    pub fn is_deleting(&self) -> bool { self.deleting_previous_state.is_some() }

    pub fn owner_id(&self) -> &UserId { self.owner.user_id() }

    /// Filename component of the final relative path, if one is reserved.
    pub fn filename(&self) -> Option<&str> { self.relative_path.as_deref().and_then(extract_filename_component) }
}

fn extract_filename_component(relative_path: &str) -> Option<&str> {
    let trimmed = relative_path.trim_end_matches('/');
    if trimmed.is_empty() {
        return None;
    }
    std::path::Path::new(trimmed).file_name().and_then(|s| s.to_str())
}

/// Monotonic revision counter for the persisted recording queue. Increments
/// once per committed queue mutation. Stored alongside the queue snapshot.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct QueueRevision(pub u64);

impl fmt::Display for QueueRevision {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { write!(f, "{}", self.0) }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_source() -> RecordingSource { RecordingSource::new("target-1", "v-1", "input-a") }

    fn test_owner() -> RecordingOwner { RecordingOwner::User(UserId::from("web:abc")) }

    #[test]
    fn legacy_recording_source_defaults_to_live_cluster() {
        let source: RecordingSource =
            serde_json::from_str(r#"{"target_id":"target","virtual_id":"42","input_name":"input-a"}"#)
                .expect("deserialize source");

        assert_eq!(source.cluster, super::super::XtreamCluster::Live);
    }

    #[test]
    fn recording_kind_serializes_as_snake_case() {
        assert_eq!(serde_json::to_string(&RecordingKind::Vod).expect("serialize"), "\"vod\"");
        assert_eq!(serde_json::to_string(&RecordingKind::Series).expect("serialize"), "\"series\"");
        assert_eq!(serde_json::to_string(&RecordingKind::Live).expect("serialize"), "\"live\"");
    }

    #[test]
    fn only_live_is_scheduled_and_only_media_is_resumable() {
        assert!(RecordingKind::Live.is_scheduled());
        assert!(!RecordingKind::Live.is_resumable());
        for kind in [RecordingKind::Vod, RecordingKind::Series] {
            assert!(!kind.is_scheduled(), "{kind} must not be scheduled");
            assert!(kind.is_resumable(), "{kind} must be resumable");
        }
    }

    #[test]
    fn live_metadata_carries_padded_interval_and_source() {
        let meta = RecordingMetadata::new_live(
            test_owner(),
            RecordingVisibility::Private,
            test_source(),
            1_700_000_000,
            1_700_000_900,
            60,
            120,
        );
        assert_eq!(meta.scheduled_start, Some(1_700_000_000 - 60));
        assert_eq!(meta.scheduled_end, Some(1_700_000_900 + 120));
        assert_eq!(meta.pre_roll_secs, 60);
        assert_eq!(meta.post_roll_secs, 120);
        assert!(!meta.is_deleting());
    }

    #[test]
    fn media_metadata_has_owner_and_source_without_live_interval() {
        let source = test_source().with_cluster(super::super::XtreamCluster::Video);
        let meta =
            RecordingMetadata::new_media(test_owner(), RecordingVisibility::Private, source, "Movie".to_string());

        assert_eq!(meta.program_title.as_deref(), Some("Movie"));
        assert!(meta.program_start.is_none());
        assert!(meta.program_end.is_none());
        assert!(meta.scheduled_start.is_none());
        assert!(meta.scheduled_end.is_none());
        assert_eq!(meta.pre_roll_secs, 0);
        assert_eq!(meta.post_roll_secs, 0);
    }

    #[test]
    fn recording_owner_round_trips_as_adjacent_tag() {
        let owner = RecordingOwner::User(UserId::from("web:alice"));
        let json = serde_json::to_string(&owner).expect("serialize");
        assert_eq!(json, r#"{"kind":"user","user":"web:alice"}"#);
        let restored: RecordingOwner = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, owner);
        assert_eq!(restored.user_id(), &UserId::from("web:alice"));
    }

    #[test]
    fn deleting_state_round_trip() {
        let mut meta =
            RecordingMetadata::new_media(test_owner(), RecordingVisibility::Private, test_source(), "M".to_string());
        assert!(!meta.is_deleting());
        meta.deleting_previous_state = Some(DeletionPreviousState::Completed);
        assert!(meta.is_deleting());
        let json = serde_json::to_string(&meta).expect("serialize");
        let restored: RecordingMetadata = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored.deleting_previous_state, Some(DeletionPreviousState::Completed));
    }

    #[test]
    fn metadata_filename_is_the_last_relative_path_component() {
        let mut meta =
            RecordingMetadata::new_media(test_owner(), RecordingVisibility::Private, test_source(), "M".to_string());
        assert_eq!(meta.filename(), None);
        meta.relative_path = Some("users/web:abc/Pilot/pilot.ts".to_string());
        assert_eq!(meta.filename(), Some("pilot.ts"));
    }

    #[test]
    fn notification_marker_serialization() {
        let marker = NotificationMarker::new(NotificationMarkerKind::Completed, 1_700_000_000);
        let json = serde_json::to_string(&marker).expect("serialize");
        assert!(json.contains("\"completed\""), "{json}");
    }

    #[test]
    fn queue_revision_default_is_zero() {
        assert_eq!(QueueRevision::default().0, 0);
        assert_eq!(format!("{}", QueueRevision(42)), "42");
    }

    // --- RecordingTaskDto ---

    fn make_dto() -> RecordingTaskDto {
        RecordingTaskDto {
            id: "rec-1".to_string(),
            title: "Pilot".to_string(),
            kind: RecordingKind::Series,
            priority: TaskPriorityDto::Normal,
            status: TransferStatusDto::Running,
            retry_attempts: 1,
            transferred_bytes: 128,
            total_bytes: Some(4096),
            next_retry_at: None,
            error: None,
            owner_id: Some(UserId::from("web:abc")),
            visibility: RecordingVisibility::Private,
            channel_id: None,
            channel_name: None,
            program_title: Some("Pilot".to_string()),
            program_start: None,
            program_end: None,
            scheduled_start: None,
            scheduled_end: None,
            pre_roll_secs: 0,
            post_roll_secs: 0,
            completed_at: None,
            filename: Some("pilot.mkv".to_string()),
            epg: Some(EpgEpisodeMetadata {
                programme_id: None,
                series_id: Some("series-1".to_string()),
                episode_id: Some("ep-1".to_string()),
                season: Some(1),
                episode: Some(2),
                airing: AiringStatus::New,
            }),
            rule_id: None,
            occurrence_key: None,
        }
    }

    #[test]
    fn recording_task_dto_round_trips_preserving_kind() {
        let dto = make_dto();
        let json = serde_json::to_string(&dto).expect("serialize");
        let restored: RecordingTaskDto = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(restored, dto);
        assert_eq!(restored.kind, RecordingKind::Series);
    }

    #[test]
    fn recording_task_dto_has_no_nested_transfer_or_recording_wrapper() {
        let json = serde_json::to_value(make_dto()).expect("serialize");
        assert!(json.get("recording").is_none(), "no nested recording wrapper");
        assert!(json.get("transfer").is_none(), "no nested transfer wrapper");
        assert_eq!(json.get("kind").and_then(serde_json::Value::as_str), Some("series"));
    }

    #[test]
    fn terminal_partition_matches_completed_failed_cancelled() {
        for status in [TransferStatusDto::Completed, TransferStatusDto::Failed, TransferStatusDto::Cancelled] {
            assert!(RecordingTaskDto { status, ..make_dto() }.is_terminal(), "{status:?} is terminal");
        }
        for status in [
            TransferStatusDto::Scheduled,
            TransferStatusDto::Queued,
            TransferStatusDto::WaitingForCapacity,
            TransferStatusDto::RetryWaiting,
            TransferStatusDto::Running,
            TransferStatusDto::Paused,
        ] {
            assert!(!RecordingTaskDto { status, ..make_dto() }.is_terminal(), "{status:?} is current");
        }
    }

    #[test]
    fn scheduled_duration_is_derived_from_the_padded_window() {
        let dto = RecordingTaskDto {
            kind: RecordingKind::Live,
            scheduled_start: Some(1_700_000_000),
            scheduled_end: Some(1_700_003_600),
            ..make_dto()
        };
        assert_eq!(dto.scheduled_duration_secs(), Some(3_600));
        assert_eq!(make_dto().scheduled_duration_secs(), None);
    }
}
