version: '3'
services:
  tuliprox:
    container_name: tuliprox
    image: ghcr.io/euzu/tuliprox:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./backup:/app/backup
      - ./downloads:/app/downloads
    environment:
      - TZ=Europe/Paris
      # - TULIPROX_ENV_FILE=/path/to/.env
    # env_file:
    #   - .env
    ports:
      - "8901:8901"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
