server:
  - name: default
    protocol: http
    host: ${env:TULIPROX_HOST_IP}
    port: "8901"
    timezone: Europe/Paris
    message: Welcome to m3u-filter
  - name: external
    protocol: https
    host: ${env:TULIPROX_DOMAIN}
    port: "443"
    timezone: Europe/Paris
    message: Welcome to m3u-filter
user:
  - target: iptv-org
    credentials:
      - username: local
        password: localsecret
        token: "77417"
        proxy: reverse
        server: default
        exp_date: 0
        max_connections: 0
        status: Active
        ui_enabled: true

      - username: external
        password: externalsecret
        token: "77418"
        proxy: reverse
        server: external
        exp_date: 0
        max_connections: 0
        status: Active
        ui_enabled: true

use_user_db: false
