mappings:
  templates:
    - name: bbc
      value: 'Title ~ "^BBC"'
    - name: documentary
      value: '(Group ~ "(Documentary|Outdoor)")'
    - name: entertainment
      value: 'Group ~ "Entertainment"'
    - name: pluto_tv
      value: '(Caption ~ "Pluto TV") AND NOT(Caption ~ "Sports")'
    - name: business
      value: 'Group ~ "Business"'

  mapping:
    - id: iptv-org
      match_as_ascii: true
      mapper:
        - filter: "!bbc!"
          script: |
            @Group = "BBC"
        - filter: "!documentary!"
          script: |
            @Group = "Documentary"
        - filter: "!entertainment!"
          script: |
            @Group = "Entertainment"
        - filter: "!pluto_tv!"
          script: |
            @Group = "Pluto TV"
        - filter: "!business!"
          script: |
            @Group = "News"
