templates:
  - name: not_red_button
    value: 'NOT (Title ~ "(?i).*red button.*")'
  - name: not_low_resolution
    value: 'NOT (Title ~ "(?i).*\(360p|240p\).*")'
  - name: all_channels
    value: 'Title ~ ".*"'
  - name: final_channel_lineup
    value: "!all_channels! AND !not_red_button! AND !not_low_resolution!"
sources:
  - inputs:
      - name: iptv-org
        type: m3u
        url: https://iptv-org.github.io/iptv/countries/uk.m3u
      - name: iptv-org
        output:
          - type: xtream
          - type: m3u
            filename: iptv.m3u
          - type: hdhomerun
            username: local
            device: hdhr1
        filter: "!final_channel_lineup!"
        options: { ignore_logo: false, share_live_streams: true }
        mapping:
          - iptv-org
