services: 
  gluetun-03:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-03
    restart: on-failure
    security_opt:
      - apparmor=docker-default   # security_opts are optional
    networks:
        - proxy-net
    expose:
        - 1080/tcp  # HTTP
        - 1388/tcp  # SOCKS5
        - 1388/udp  # SOCKS5
        - 9388/tcp  # SHADOWSOCKS
        - 9388/udp  # SHADOWSOCKS
        #- 8888/tcp  # METRICS
    cap_add:
        - NET_ADMIN
    env_file: 
        - ../.env.http-proxy
        - ../.env.ss-proxy
        - .env.wg-03
    volumes:
        - ./conf:/gluetun/
    devices:
        - /dev/net/tun:/dev/net/tun
    environment:
        - TZ=America/Chicago
        - UPDATER_PERIOD=24h
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 1

  socks5-03:
    image: serjs/go-socks5-proxy
    container_name: socks5-03
    restart: on-failure
    security_opt: 
      - apparmor=docker-default   # security_opts are optional
    network_mode: service:gluetun-03
    env_file: ../.env.socks5-proxy
    depends_on:
      gluetun-03:
        condition: service_healthy
        restart: true

networks:
    proxy-net:
        external: true
        name: proxy-net	
