http:
  middlewares:
    cs-bouncer-traefik-plugin:
      plugin:
        cs-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          LogFilePath: "/var/log/traefik/cs-bouncer-traefik-plugin.log"
          updateIntervalSeconds: 60
          updateMaxFailure: 0
          defaultDecisionSeconds: 60
          remediationStatusCode: 403
          httpTimeoutSeconds: 10

          ### Crowdsec Appsec Configuration ###
          crowdsecMode: appsec  # none live stream alone appsec -> https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecPath: "/"
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecAppsecBodyLimit: 10485760

          ### Crowdsec LAPI Configuration ###
          crowdsecLapiKey: <crowdsec-bouncer-key>
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiPath: "/"
          crowdsecLapiTLSInsecureVerify: false
          # crowdsecLapiTLSCertificateAuthority:
          # crowdsecLapiTLSCertificateBouncer:
          # crowdsecLapiTLSCertificateBouncerKey:

          ### Crowdsec CAPI Configuration ###
          # crowdsecCapiMachineId: login
          # crowdsecCapiPassword: password
          # crowdsecCapiScenarios:
          #   - crowdsecurity/http-cve 
          #   - crowdsecurity/base-http-scenarios 
          #   - crowdsecurity/http-path-traversal-probing
          #   - crowdsecurity/http-xss-probing
          #   - crowdsecurity/http-generic-bf
          #   - crowdsecurity/traefik 

          ### Crowdsec Client Configuration ###
          forwardedHeadersTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
          forwardedHeadersCustomName: X-Forwarded-For
          remediationHeadersCustomName: cs-remediation

          ### Crowdsec redis Configuration ###
          # redisCacheEnabled: false
          # redisCacheHost: "redis:6379"
          # redisCachePassword: password
          # redisCacheDatabase: "5"
          # redisCacheUnreachableBlock: true

          ### Crowdsec captcha Configuration ###
          # captchaProvider: hcaptcha
          # captchaSiteKey: FIXME
          # captchaSecretKey: FIXME
          # captchaGracePeriodSeconds: 1800
          # captchaHTMLFilePath: /captcha.html
          # banHTMLFilePath: /ban.html

          ### Crowdsec metrics Configuration ###
          metricsUpdateIntervalSeconds: 600