[package]
name = "tuliprox-config-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Application configuration bootstrap for tuliprox"

[lints]
workspace = true

[dependencies]
shared = { workspace = true }
tuliprox-core = { workspace = true }
tuliprox-repository = { workspace = true }
arc-swap.workspace = true
blake3.workspace = true
chrono.workspace = true
log.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value", "preserve_order"] }
serde-saphyr.workspace = true
tempfile = "3.27.0"
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "macros"] }
url.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }
