[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2"
serde = { version = "1", features = ["derive"] }
rand = "0"
regex = "1"
enum-iterator = "2"
log = "0"
path-clean = "1"
url = "2"
indexmap = "2"
pest = "2"
pest_derive = "2.8"
serde_json = "1"
base64 = "0"
blake3 = "1"
clap = { version = "4.5.40", features = ["derive"] }