[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2"
serde = { version = "1", features = ["derive"] }
regex = "1"
enum-iterator = "2"
log = "0"
path-clean = "1"
url = "2"
indexmap = "2"
pest = "2"
pest_derive = "2"
serde_json = "1"
base64 = "0"
blake3 = "1"
fastrand = "2"
zeroize = "1"
chrono = "0.4.41"
bytes = "1"
bincode = "2"
