WHITESPACE = _{ " " | "\t" | "\r" | "\n"}
field = { ^"group" | ^"title" | ^"name" | ^"genre" | ^"url" | ^"input" | ^"caption" | ^"epgid"}
numeric_field = { ^"chno" | ^"quality" }
and = { ^"and" }
or = { ^"or" }
not = { ^"not" }
regexp = @{ "\"" ~ ( "\\\"" | (!"\"" ~ ANY) )* ~ "\"" }
number = @{ ASCII_DIGIT+ }
type_value = { ^"live" | ^"vod" | ^"movie" | ^"series" }
type_comparison = { ^"type" ~ "=" ~ type_value }
field_comparison_value = _{ regexp }
field_comparison = { field ~ "~" ~ field_comparison_value }
str_op = { "!=" | "=" | ^"contains" | ^"startswith" }
string_comparison = { field ~ str_op ~ regexp }
presence_negation = { ^"not" }
presence_op = { (^"is" ~ presence_negation?) | "!=" | "=" }
presence_comparison = { field ~ presence_op ~ ^"empty" }
num_op = { ">=" | "<=" | "!=" | ">" | "<" | "=" }
numeric_comparison = { numeric_field ~ num_op ~ number }
set_values = { regexp ~ ("," ~ regexp)* }
set_comparison = { field ~ ^"in" ~ "[" ~ set_values ~ "]" }
comparison = { field_comparison | type_comparison | numeric_comparison | set_comparison | presence_comparison | string_comparison }
bool_op = { and | or }
expr_group = { "(" ~ expr ~ ")" }
basic_expr = _{ comparison | expr_group }
not_expr = _{ not ~ basic_expr }
expr = {
  not_expr ~ (bool_op ~ expr)?
  | basic_expr ~ (bool_op ~ expr)*
}
stmt = { expr ~ (bool_op ~ expr)* }
main = _{ SOI ~ stmt ~ EOI }
