####
#### this section is optional if you run tuliprox behind a path prefix
####


http:
  routers:
    cdn-root-web:
      rule: "Host(`cdn.tuliprox.io`)" # change to your domain
      entryPoints: 
        - web
      service: noop@internal

    cdn-root-websecure:
      rule: "Host(`cdn.tuliprox.io`)" # change to your domain
      entryPoints:
        - websecure
      service: noop@internal     