http:
  middlewares:
    strip-forward-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Port: 0
          X-Forwarded-Proto: ""
          X-Forwarded-Server: ""
          X-Forwarded-Host: ""
          X-Forwarded-For: ""     
          X-Real-IP:      ""      