name: Docker Build and Push

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Install trunk
      run: |
        wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.8/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        sudo mv trunk /usr/local/bin/
    
    - name: Add Rust targets
      run: |
        rustup target add x86_64-unknown-linux-musl
        rustup target add aarch64-unknown-linux-musl
        rustup target add wasm32-unknown-unknown
    
    - name: Create GHCR_IO config
      run: |
        mkdir -p $HOME
        echo "GHCR_IO_TOKEN=${{ secrets.GHCR_IO_TOKEN }}" > $HOME/.ghcr.io
    
    - name: Make scripts executable
      run: |
        chmod +x bin/build_github_docker.sh
        chmod +x bin/build_resources.sh
    
    - name: Run master build script
      run: ./bin/build_github_docker.sh

  build-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build-script:
          - build_github_docker_aarch64.sh
          - build_github_docker_beta.sh
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Install trunk
      run: |
        wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.8/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        sudo mv trunk /usr/local/bin/
    
    - name: Add Rust targets
      run: |
        rustup target add x86_64-unknown-linux-musl
        rustup target add aarch64-unknown-linux-musl
        rustup target add wasm32-unknown-unknown
    
    - name: Create GHCR_IO config
      run: |
        mkdir -p $HOME
        echo "GHCR_IO_TOKEN=${{ secrets.GHCR_IO_TOKEN }}" > $HOME/.ghcr.io
    
    - name: Make scripts executable
      run: |
        chmod +x bin/${{ matrix.build-script }}
        chmod +x bin/build_resources.sh
    
    - name: Run develop build script
      run: ./bin/${{ matrix.build-script }}
