name: Docker Build and Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl
      
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      
      - name: Install trunk
        run: cargo install trunk
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      - name: Create GHCR token file
        run: |
          mkdir -p $HOME
          echo "GHCR_IO_TOKEN=${{ secrets.GHCR_IO_TOKEN }}" > $HOME/.ghcr.io
      
      - name: Make build script executable
        run: chmod +x ./bin/build_docker.sh
      
      - name: Build and push Docker images
        run: ./bin/build_docker.sh ${{ steps.extract_branch.outputs.branch }}
